controle_financeiro/contas/urls.py
from django.urls import path

from .views import (ContaAtualizar, ContaCriar, ContaDetalhe,
                    ContaExcluir, ContaLista)

app_name = 'contas'

urlpatterns = [
    path('', ContaLista.as_view(), name='listar'),
    path('criar', ContaCriar.as_view(), name='criar'),
    path('<slug:slug>', ContaDetalhe.as_view(), name='detalhar'),
    path('<slug:slug>/editar', ContaAtualizar.as_view(), name='editar'),
    path('<slug:slug>/excluir', ContaExcluir.as_view(), name='excluir'),
]

controle_financeiro/lancamentos/urls.py
from django.urls import path

from .views import (LancamentoCriar, LancamentoDetalhe, LancamentoExcluir,
                    LancamentoLista)

app_name = "lancamentos"

urlpatterns = [
    path("", LancamentoLista.as_view(), name="listar"),
    path("criar", LancamentoCriar.as_view(), name="criar"),
    path("<int:pk>", LancamentoDetalhe.as_view(), name="detalhar"),
    path("<int:pk>/excluir", LancamentoExcluir.as_view(), name="excluir"),
]

controle_financeiro/lancamentos/models.py
from decimal import Decimal

from base.models import BaseModel
from carteiras.models import CentroCusto
from django.core.validators import MinValueValidator
from django.db import models


class Categoria(BaseModel):

    titulo = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    descricao = models.TextField()

    class Meta:
        ordering = ["slug"]
        indexes = [
            models.Index(fields=["slug"]),
        ]

    def __str__(self):
        return f"{self.titulo}"


class Lancamento(BaseModel):

    TIPO_RECEITA = 1
    TIPO_DESPESA = 2

    TIPOS_ESCOLHAS = [
        (TIPO_RECEITA, "Receita"),
        (TIPO_DESPESA, "Despesa"),
    ]

    tipo = models.IntegerField(choices=TIPOS_ESCOLHAS)
    categorias = models.ManyToManyField(Categoria, blank=True)
    datahora = models.DateTimeField()

    centro_custo = models.ForeignKey(
        CentroCusto, on_delete=models.CASCADE, related_name="lancamentos"
    )

    class Meta:
        ordering = ["-datahora"]

    def __str__(self):
        tipo_desc = "Receita" if self.tipo == Lancamento.TIPO_RECEITA else "Despesa"
        return f"{self.pk} - {tipo_desc} (Centro de custo {self.centro_custo.pk})"

    @property
    def e_despesa(self) -> bool:
        return hasattr(self, "despesa")

    @property
    def e_receita(self) -> bool:
        return hasattr(self, "receita")

    @property
    def descricao(self) -> str:
        if self.e_despesa:
            descricao = f"Despesa {self.despesa.nome}"
        elif self.e_receita:
            descricao = f"Receita {self.receita.nome}"
        else:
            descricao = "N/A"
        return descricao

    @property
    def valor(self) -> Decimal:
        if self.e_despesa:
            valor = self.despesa.valor_total * -1
        elif self.e_receita:
            valor = self.receita.valor_total
        else:
            valor = Decimal("0.0")
        return valor


class Receita(BaseModel):

    nome = models.CharField(max_length=100)
    valor_total = models.DecimalField(max_digits=11, decimal_places=2, default=0)
    datahora = models.DateTimeField()

    lancamento = models.OneToOneField(
        Lancamento, on_delete=models.CASCADE, related_name="receita"
    )

    class Meta:
        ordering = ["-datahora"]

    def __str__(self):
        return f"{self.pk} - {self.nome} (Lancamento {self.lancamento.pk})"


class Despesa(BaseModel):

    SITUACAO_ABERTO = 1
    SITUACAO_PAGO = 2
    SITUACAO_CANCELADO = 3
    SITUACAO_ESTORNADO = 4

    SITUACOES_ESCOLHAS = [
        (SITUACAO_ABERTO, "Em Aberto"),
        (SITUACAO_PAGO, "Pago"),
        (SITUACAO_CANCELADO, "Cancelado"),
        (SITUACAO_ESTORNADO, "Estornado"),
    ]

    nome = models.CharField(max_length=100)
    valor_total = models.DecimalField(max_digits=11, decimal_places=2)
    datahora = models.DateTimeField()
    quantidade_parcelas = models.IntegerField(default=1)
    situacao = models.IntegerField(
        choices=SITUACOES_ESCOLHAS, default=SITUACAO_ABERTO
    )

    lancamento = models.OneToOneField(
        Lancamento, on_delete=models.CASCADE, related_name="despesa"
    )

    class Meta:
        ordering = ["-datahora"]

    def __str__(self):
        return f"{self.pk} - {self.nome} (Lancamento {self.lancamento.pk})"


class Parcela(BaseModel):

    SITUACAO_ABERTO = 1
    SITUACAO_PAGO = 2
    SITUACAO_CANCELADO = 3
    SITUACAO_ESTORNADO = 4

    SITUACOES_ESCOLHAS = [
        (SITUACAO_ABERTO, "Em Aberto"),
        (SITUACAO_PAGO, "Pago"),
        (SITUACAO_CANCELADO, "Cancelado"),
        (SITUACAO_ESTORNADO, "Estornado"),
    ]

    ordem = models.IntegerField(validators=[MinValueValidator(1)])
    data = models.DateField()
    valor = models.DecimalField(max_digits=11, decimal_places=2)
    situacao = models.IntegerField(choices=SITUACOES_ESCOLHAS, default=SITUACAO_ABERTO)

    despesa = models.ForeignKey(
        Despesa, on_delete=models.CASCADE, related_name="parcelas"
    )

    class Meta:
        ordering = ["data"]

    def __str__(self):
        return f"{self.pk} - {self.ordem}ª parcela (Despesa: {self.despesa.pk})"

controle_financeiro/lancamentos/forms.py
from base.forms.monetary import MonetaryField
from carteiras.models import CentroCusto
from django import forms
from django.core.exceptions import ValidationError

from .models import Despesa, Lancamento, Receita


class CentroCustoAttrs(forms.Select):
    def create_option(
        self, name, value, label, selected, index, subindex=None, attrs=None
    ):
        option = super().create_option(
            name, value, label, selected, index, subindex, attrs
        )
        if value:
            centro_custo = value.instance
            option["attrs"].update(
                {
                    "pode-parcelar": centro_custo.pode_parcelar,
                    "e-cartao": centro_custo.e_cartao,
                    "e-conta": centro_custo.e_conta,
                }
            )
        return option


class LancamentoForm(forms.ModelForm):
    prefix = "lancamento"

    id = forms.IntegerField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = Lancamento
        fields = ["id", "tipo", "categorias", "centro_custo"]
        labels = {
            "tipo": "Tipo",
            "categorias": "Categorias",
            "centro_custo": "Centro de Custo",
        }
        widgets = {"centro_custo": CentroCustoAttrs}

    def __init__(self, *args, **kwargs):
        carteira = kwargs.pop("carteira", None)
        super().__init__(*args, **kwargs)
        self.fields["centro_custo"].queryset = CentroCusto.objects.filter(
            carteira=carteira
        ).all()


class ReceitaForm(forms.ModelForm):
    prefix = "receita"

    id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    valor_total = MonetaryField(required=True)

    class Meta:
        model = Receita
        fields = ["id", "nome", "valor_total", "datahora"]
        labels = {
            "tipo": "Nome",
            "valor_total": "Valor Total",
            "datahora": "Data e Hora",
        }
        widgets = {
            "datahora": forms.DateTimeInput(
                format="%Y-%m-%dT%H:%M:%S", attrs={"type": "datetime-local"}
            ),
        }


class DespesaForm(forms.ModelForm):
    prefix = "despesa"

    id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    valor_total = MonetaryField(required=True)

    class Meta:
        model = Despesa
        fields = [
            "id",
            "nome",
            "valor_total",
            "datahora",
            "quantidade_parcelas",
        ]
        labels = {
            "tipo": "Nome",
            "valor_total": "Valor Total",
            "datahora": "Data e Hora",
            "quantidade_parcelas": "Qtde. Parcelas",
        }
        widgets = {
            "datahora": forms.DateTimeInput(
                format="%Y-%m-%dT%H:%M:%S", attrs={"type": "datetime-local"}
            ),
        }

    def __init__(self, *args, **kwargs):
        centro_custo = kwargs.pop("centro_custo", None)
        super().__init__(*args, **kwargs)
        self.cartao = centro_custo.cartao if hasattr(centro_custo, "cartao") else None

    def clean(self):
        if self.cartao and not self.cartao.tem_limite(self.cleaned_data["valor_total"]):
            raise ValidationError("Valor total ultrapassa limite do cartão!")

controle_financeiro/lancamentos/views.py
from typing import Any, Dict

from base.views import LoginRequiredBase
from carteiras.models import Carteira
from carteiras.usecases import (adicionar_despesa_no_centro_custo,
                                adicionar_receita_no_centro_custo)
from django.conf import settings
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, View
from django.views.generic.edit import DeleteView

from .forms import DespesaForm, LancamentoForm, ReceitaForm
from .models import Lancamento
from .usecases import criar_nova_despesa, criar_nova_receita


class LancamentoLista(LoginRequiredBase, ListView):
    model = Lancamento
    template_name = "lancamentos/lancamento_lista.html"
    context_object_name = "lancamentos"
    fields = ["despesa", "receita"]
    paginate_by = settings.REGISTROS_POR_PAGINA

    def get_queryset(self, *args, **kwargs) -> QuerySet:
        return Lancamento.objects.select_related(
            "centro_custo", "centro_custo__carteira"
        ).filter(
            centro_custo__carteira__slug=self.kwargs.get("carteira_slug"),
            centro_custo__carteira__usuario_id=self.request.user.pk,
        )

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(*args, **kwargs)
        context.update(self.kwargs)
        context["href_voltar"] = reverse_lazy(
            "carteiras:detalhar",
            kwargs={"slug": self.kwargs.get("carteira_slug")},
        )
        if not context.get("lancamentos").exists():
            context["redirecionar"] = context["href_voltar"]
        return context


class LancamentoDetalhe(LoginRequiredBase, View):
    template_name = "lancamentos/lancamento_detalhe.html"

    def get_queryset(self, *args, **kwargs) -> QuerySet:
        carteira_slug = self.kwargs.get("carteira_slug")
        usuario_pk = self.request.user.pk
        return Lancamento.objects.select_related(
            "centro_custo",
            "centro_custo__carteira",
        ).prefetch_related(
            "despesa__parcelas"
        ).filter(
            centro_custo__carteira__slug=carteira_slug,
            centro_custo__carteira__usuario_id=usuario_pk,
        )

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        context = {
            "href_voltar": reverse_lazy(
                "carteiras:lancamentos:listar",
                kwargs={"carteira_slug": kwargs.get("carteira_slug")},
            ),
            **kwargs,
        }
        context["lancamento"] = self.get_queryset(*args, **kwargs).get(
            pk=kwargs.get("pk")
        )
        if context["lancamento"].tipo == Lancamento.TIPO_DESPESA:
            context["despesa"] = context["lancamento"].despesa
            context["parcelas"] = context["lancamento"].despesa.parcelas.all()
        else:
            context["receita"] = context["lancamento"].receita
        return context

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        return render(
            request, self.template_name, self.get_context_data(*args, **kwargs)
        )


class LancamentoCriar(LoginRequiredBase, View):
    template_name = "lancamentos/lancamento_criar.html"

    def get_success_url(self) -> HttpResponse:
        return reverse_lazy(
            "carteiras:lancamentos:listar",
            kwargs={"carteira_slug": self.kwargs.get("carteira_slug")},
        )

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        carteira_slug = kwargs.get("carteira_slug")
        carteira = get_object_or_404(
            Carteira, slug=carteira_slug, usuario_id=self.request.user.pk
        )
        context = {
            "lancamento_form": kwargs.pop(
                "lancamento_form", LancamentoForm(carteira=carteira)
            ),
            "receita_form": kwargs.pop("receita_form", ReceitaForm()),
            "despesa_form": kwargs.pop("despesa_form", DespesaForm()),
            "tipos_lancamento": ",".join(
                [form.prefix for form in (ReceitaForm, DespesaForm)]
            ),
            "href_voltar": reverse_lazy(
                "carteiras:detalhar",
                kwargs={"slug": carteira_slug},
            ),
        }
        context.update(kwargs)
        return context

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        return render(
            request, self.template_name, self.get_context_data(*args, **kwargs)
        )

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:

        contexto_erro = {}
        carteira = get_object_or_404(
            Carteira, slug=kwargs.get("carteira_slug"), usuario_id=request.user.pk
        )

        lancamento_form = LancamentoForm(request.POST, carteira=carteira)
        if lancamento_form.is_valid():
            lancamento = lancamento_form.save(commit=False)
        else:
            contexto_erro["lancamento_form"] = lancamento_form

        if (
            not contexto_erro
            and lancamento_form.cleaned_data["tipo"] == Lancamento.TIPO_RECEITA
        ):
            receita_form = ReceitaForm(request.POST)
            if receita_form.is_valid():
                receita = receita_form.save(commit=False)
                criar_nova_receita(
                    lancamento=lancamento, receita=receita, carteira=carteira
                )
            else:
                contexto_erro["receita_form"] = receita_form

        if (
            not contexto_erro
            and lancamento_form.cleaned_data["tipo"] == Lancamento.TIPO_DESPESA
        ):
            despesa_form = DespesaForm(
                request.POST, centro_custo=lancamento.centro_custo
            )
            if despesa_form.is_valid():
                despesa = despesa_form.save(commit=False)
                criar_nova_despesa(
                    lancamento=lancamento, despesa=despesa, carteira=carteira
                )
            else:
                contexto_erro["despesa_form"] = despesa_form

        if contexto_erro:
            return render(
                request,
                self.template_name,
                self.get_context_data(*args, **kwargs, **contexto_erro),
            )
        else:
            return redirect(self.get_success_url())


class LancamentoExcluir(LoginRequiredBase, DeleteView):
    model = Lancamento
    form_class = LancamentoForm
    template_name = "lancamentos/lancamento_excluir.html"
    context_object_name = "lancamento"

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(*args, **kwargs)
        context.update(self.kwargs)
        context["href_voltar"] = reverse_lazy(
            "carteiras:detalhar",
            kwargs={"slug": self.kwargs.get("carteira_slug")},
        )
        return context

    def get_success_url(self) -> str:
        return reverse_lazy(
            "carteiras:lancamentos:listar",
            kwargs={"carteira_slug": self.kwargs.get("carteira_slug")},
        )

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        lancamento = get_object_or_404(Lancamento, pk=kwargs.get("pk"))
        if lancamento.tipo == Lancamento.TIPO_RECEITA:
            adicionar_despesa_no_centro_custo(lancamento.centro_custo, lancamento.receita.valor_total)
        else:
            adicionar_receita_no_centro_custo(lancamento.centro_custo, lancamento.despesa.valor_total)
        lancamento.delete()
        return redirect(self.get_success_url())

controle_financeiro/lancamentos/templates/despesas/despesa_atualizar.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block titulo %}lancamentos{% endblock %}

{% block cabecalho %}
<div class="container">
    <h1>Lancamento</h1>
    <p>Atualizar Lancamento registrada.</p>
</div>
{% endblock %}

{% block conteudo %}
{% if form.subject.errors %}
<ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
</ol>
{% endif %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" role="button" type="submit" value="Atualizar">
    <div style="float: right;">
        <a class="btn btn-outline-primary" role="button" href="{% url 'lancamentos:listar' %}">Cancelar</a>
    </div>
</form>
{% endblock %}

controle_financeiro/lancamentos/templates/despesas/despesa_criar.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block titulo %}lancamentos{% endblock %}

{% block cabecalho %}
<div class="container">
    <h1>Lancamento</h1>
    <p>Cadastre sua Lancamento.</p>
</div>
{% endblock %}

{% block conteudo %}
{% if form.subject.errors %}
<ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
</ol>
{% endif %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" role="button" type="submit" value="Gravar">
    <div style="float: right;">
        <a class="btn btn-outline-primary" role="button" href="{% url 'lancamentos:listar' %}">Cancelar</a>
    </div>
</form>
{% endblock %}

controle_financeiro/lancamentos/templates/despesas/despesa_detalhe.html
{% extends "base/base.html" %}
{% load transformar_em_texto %}
{% load Lancamento_calculos %}
{% load humanize %}

{% block titulo %}lancamentos{% endblock %}

{% block cabecalho %}
<div class="container">
  <h1>Lancamento</h1>
  <p>Detalhamento da Lancamento registrada.</p>
</div>
{% endblock %}

{% block conteudo %}
<form>
  <fieldset disabled>
    <div class="mb-3">
      <label for="inputDataHora" class="form-label">Data e Hora</label>
      <input type="datetime-local" id="inputDataHora" class="form-control"
        value="{{ Lancamento.datahora|datetime_para_texto }}">
    </div>
    <div class="mb-3">
      <label for="inputDescricao" class="form-label">Descrição</label>
      <input type="text" id="inputDescricao" class="form-control" value="{{ Lancamento.descricao|safe }}">
    </div>
    <div class="mb-3">
      <label for="inputParcelado" class="form-label">Parcelado</label>
      <input type="text" id="inputParcelado" class="form-control" value="{{ Lancamento.parcelado }}">
    </div>
    <div class="mb-3">
      <label for="inputValor" class="form-label">Valor</label>
      <input type="text" id="inputValor" class="form-control" aria-describedby="valorAjuda"
        value="R$ {{ object|calcular_parcela|intcomma }}">
      <small id="valorAjuda" class="form-text text-muted">Se for parcelado, será apresentado o valor da parcela.</small>
    </div>
    <div class="mb-3">
      <label for="inputCategoria" class="form-label">Categoria</label>
      <input type="text" id="inputCategoria" class="form-control" value="{{ Lancamento.categorias|queryset_para_texto }}">
    </div>
    <div class="mb-3">
      <label for="inputCriadoEm" class="form-label">Criado em</label>
      <input type="datetime-local" id="inputCriadoEm" class="form-control"
        value="{{ Lancamento.criado_em|datetime_para_texto }}">
    </div>
    <div class="mb-3">
      <label for="inputAtualizadoEm" class="form-label">Atualizado em</label>
      <input type="datetime-local" id="inputAtualizadoEm" class="form-control"
        value="{{ Lancamento.atualizado_em|datetime_para_texto }}">
    </div>
  </fieldset>
</form>
<div style="float: left; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button" href="{% url 'lancamentos:editar' Lancamento.id %}">Editar</a>
</div>
<div style="float: left; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button" href="{% url 'lancamentos:excluir' Lancamento.id %}">Excluir</a>
</div>
<div style="float: right; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button" href="{% url 'lancamentos:listar' %}">Voltar</a>
</div>
{% endblock %}

controle_financeiro/lancamentos/templates/despesas/despesa_excluir.html
{% extends "base/base.html" %}

{% block titulo %}lancamentos{% endblock %}

{% block cabecalho %}
<div class="container">
    <div class="bd-intro ps-lg-4">
        <div class="d-md-flex flex-md-row-reverse align-items-center justify-content-between">
            <h1>Lancamento</h1>
        </div>
    </div>
</div>
{% endblock %}

{% block conteudo %}
    {% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
    {% endif %}    
    <form method="post">{% csrf_token %}
        <p>
            Você tem certeza que quer apagar a Lancamento <strong>{{ Lancamento.descricao|truncatechars:30 }}</strong>?
        </p>
        <input class="btn btn-primary" role="button" type="submit" value="Apagar">
        <div style="float: right;">
            <a class="btn btn-outline-primary" role="button" href="{% url 'lancamentos:listar' %}">Cancelar</a>
        </div>
    </form>
{% endblock %}

controle_financeiro/lancamentos/templates/despesas/despesa_lista.html
{% extends "base/base.html" %}
{% load transformar_em_texto %}
{% load Lancamento_calculos %}
{% load humanize %}

{% block titulo %}lancamentos{% endblock %}

{% block cabecalho %}
<div class="container">
    <h1>Lancamento</h1>
    <p>Lista de lancamentos registradas.</p>
</div>
{% endblock %}

{% block conteudo %}
<div style="float: right;">
    <p>
        <a class="btn btn-primary" role="button" href="{% url 'lancamentos:criar' %}">Criar</a>
    </p>
</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Data</th>
            <th scope="col">Descrição</th>
            <th scope="col">Valor</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for Lancamento in lancamentos %}
        <tr onclick="window.location='{% url 'lancamentos:detalhar' Lancamento.id %}'">
            <td>{{ Lancamento.datahora|date:'d/m/Y H:i' }}</td>
            <td>{{ Lancamento.descricao|truncatechars:14 }}</td>
            <td>{{ Lancamento|calcular_parcela|intcomma }}</td>
            <td>
                <a href="{% url 'lancamentos:editar' Lancamento.id %}">editar</a>
                <a href="{% url 'lancamentos:excluir' Lancamento.id %}">excluir</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% include 'base/paginacao.html' %}

{% endblock %}