controle_financeiro/carteiras/urls.py
from django.urls import include, path

from .views import (
    CarteiraAtualizar,
    CarteiraCriar,
    CarteiraDetalhe,
    CarteiraDetalheOld,
    CarteiraExcluir,
    CarteiraLista,
)

app_name = "carteiras"

urlpatterns = [
    path("", CarteiraLista.as_view(), name="listar"),
    path("criar", CarteiraCriar.as_view(), name="criar"),
    path("<slug:slug>", CarteiraDetalhe.as_view(), name="detalhar"),
    path("<slug:slug>/detalhar", CarteiraDetalheOld.as_view(), name="detalhar_old"),
    path("<slug:slug>/editar", CarteiraAtualizar.as_view(), name="editar"),
    path("<slug:slug>/excluir", CarteiraExcluir.as_view(), name="excluir"),
    path("<slug:carteira_slug>/cartoes/", include("cartoes.urls", namespace="cartoes")),
    path("<slug:carteira_slug>/contas/", include("contas.urls", namespace="contas")),
    path("<slug:carteira_slug>/lancamentos/", include("lancamentos.urls", namespace="lancamentos")),
]

controle_financeiro/contas/urls.py
from django.urls import path

from .views import (ContaAtualizar, ContaCriar, ContaDetalhe,
                    ContaExcluir, ContaLista)

app_name = 'contas'

urlpatterns = [
    path('', ContaLista.as_view(), name='listar'),
    path('criar', ContaCriar.as_view(), name='criar'),
    path('<slug:slug>', ContaDetalhe.as_view(), name='detalhar'),
    path('<slug:slug>/editar', ContaAtualizar.as_view(), name='editar'),
    path('<slug:slug>/excluir', ContaExcluir.as_view(), name='excluir'),
]

controle_financeiro/carteiras/models.py
from base.models import BaseModel
from django.db import models
from usuarios.models import Usuario


class Carteira(BaseModel):

    nome = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    principal = models.BooleanField(default=False)

    usuario = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, related_name="usuario"
    )

    class Meta:
        ordering = ["nome"]
        unique_together = (
            ("usuario_id", "id"),
            ("usuario_id", "slug"),
        )
        indexes = [
            models.Index(fields=["usuario_id", "id"]),
            models.Index(fields=["usuario_id", "slug"]),
        ]

    def __str__(self):
        return f"{self.nome}"

    @property
    def tem_centro_custos(self) -> bool:
        return self.centro_custos.exists()

    @property
    def tem_cartoes(self) -> bool:
        return self.centro_custos.filter(tipo=CentroCusto.TIPO_CARTAO).exists()

    @property
    def tem_contas(self) -> bool:
        return self.centro_custos.filter(tipo=CentroCusto.TIPO_CONTA).exists()

    @property
    def tem_lancamentos(self) -> bool:
        return self.centro_custos.exclude(lancamentos__isnull=True).exists()


class CentroCusto(BaseModel):

    TIPO_CONTA = 1
    TIPO_CARTAO = 2

    TIPOS_ESCOLHAS = [
        (TIPO_CONTA, "Conta"),
        (TIPO_CARTAO, "Cartão"),
    ]

    tipo = models.IntegerField(choices=TIPOS_ESCOLHAS)

    carteira = models.ForeignKey(
        Carteira, on_delete=models.CASCADE, related_name="centro_custos"
    )

    class Meta:
        unique_together = (("carteira_id", "id"),)
        indexes = [
            models.Index(fields=["carteira_id", "id"]),
        ]

    def __str__(self) -> str:
        return self.descricao

    @property
    def e_cartao(self) -> bool:
        return hasattr(self, "cartao")

    @property
    def e_conta(self) -> bool:
        return hasattr(self, "conta")


    @property
    def slug(self) -> str:
        if self.e_cartao:
            valor_total = self.cartao.slug
        elif self.e_conta:
            valor_total = self.conta.slug
        else:
            valor_total = 0.0
        return valor_total

    @property
    def descricao(self) -> str:
        if self.e_cartao:
            descricao = f"Cartão {str(self.cartao)}"
        elif self.e_conta:
            descricao = f"Conta {str(self.conta)}"
        else:
            descricao = "N/A"
        return descricao

    @property
    def valor_total(self) -> str:
        if self.e_cartao:
            valor_total = self.cartao.valor_total
        elif self.e_conta:
            valor_total = self.conta.valor_total
        else:
            valor_total = 0.0
        return valor_total

    @property
    def tem_lancamentos(self) -> bool:
        return self.lancamentos.exists()

    @property
    def pode_parcelar(self) -> bool:
        if self.e_cartao:
            pode_parcelar = self.cartao.pode_parcelar
        else:
            pode_parcelar = False
        return pode_parcelar

controle_financeiro/carteiras/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.template.defaultfilters import slugify

from .models import Carteira


class CarteiraForm(forms.ModelForm):

    slug = forms.CharField(widget=forms.HiddenInput, max_length=100, required=False)

    class Meta:
        model = Carteira
        fields = ["nome", "slug"]
        labels = {
            "nome": "Nome",
        }

    def __init__(self, *args, **kwargs):
        self.queryset = kwargs.pop("queryset", None)
        super().__init__(*args, **kwargs)

    def _existe_slug(self):
        if (
            self.queryset
            and self.queryset.filter(slug=self.cleaned_data["slug"]).exists()
        ):
            raise ValidationError("Já existe carteira com esse nome!")

    def clean(self):
        self.cleaned_data["slug"] = slugify(self.cleaned_data["nome"])
        if self.instance:
            if self.instance.slug != self.cleaned_data["slug"]:
                self._existe_slug()
        else:
            self._existe_slug()

controle_financeiro/carteiras/views.py
from typing import Any, Dict, Optional

from base.views import LoginRequiredBase
from django.conf import settings
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import CarteiraForm
from .models import Carteira
from lancamentos.models import Lancamento


class CarteiraLista(LoginRequiredBase, ListView):
    model = Carteira
    template_name = "carteiras/carteira_lista.html"
    fields = ["nome"]
    context_object_name = "carteiras"
    paginate_by = settings.REGISTROS_POR_PAGINA

    def get_queryset(self) -> QuerySet:
        return Carteira.objects.filter(usuario_id=self.request.user.pk)

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(*args, **kwargs)
        context.update(self.kwargs)
        context["href_voltar"] = reverse_lazy("gerenciamento:index")
        if not context.get("carteiras").exists():
            context["redirecionar"] = context["href_voltar"]
        return context


class CarteiraDetalhe(LoginRequiredBase, DetailView):
    model = Carteira
    context_object_name = "carteira"
    template_name = "carteiras/carteira_detalhe.html"

    QTDE_LANCAMENTOS = 5

    def get_queryset(self) -> QuerySet:
        return Carteira.objects.prefetch_related("centro_custos").filter(usuario_id=self.request.user.pk)

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(*args, **kwargs)
        context.update(self.kwargs)
        context["centro_custos"] = context["carteira"].centro_custos.select_related("cartao", "conta").all()
        queryset = Lancamento.objects.select_related("receita", "despesa", "centro_custo").filter(centro_custo__in=context["centro_custos"])
        context["lancamentos"] = queryset.order_by("-datahora")[:self.QTDE_LANCAMENTOS]
        context["lancamentos_continua"] = True if queryset.count() > self.QTDE_LANCAMENTOS else False
        return context


class CarteiraDetalheOld(LoginRequiredBase, DetailView):
    model = Carteira
    template_name = "carteiras/carteira_detalhe_old.html"
    context_object_name = "carteira"

    def get_queryset(self) -> QuerySet:
        return Carteira.objects.filter(usuario_id=self.request.user.pk)

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(*args, **kwargs)
        context.update(self.kwargs)
        context["href_voltar"] = reverse_lazy("carteiras:listar")
        return context


class CarteiraCriar(LoginRequiredBase, CreateView):
    model = Carteira
    form_class = CarteiraForm
    template_name = "carteiras/carteira_criar.html"
    context_object_name = "carteira"

    def get_queryset(self) -> QuerySet:
        return Carteira.objects.filter(usuario_id=self.request.user.pk)

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(*args, **kwargs)
        context.update(self.kwargs)
        context["href_voltar"] = reverse_lazy("carteiras:listar")
        return context

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        form = CarteiraForm(request.POST, queryset=self.get_queryset(*args, **kwargs))
        if form.is_valid():
            carteira = form.save(commit=False)
            carteira.usuario_id = request.user.pk
            form.save()
            return redirect("carteiras:listar")
        else:
            return render(request, self.template_name, {"form": form})


class CarteiraAtualizar(LoginRequiredBase, UpdateView):
    model = Carteira
    form_class = CarteiraForm
    template_name = "carteiras/carteira_atualizar.html"
    context_object_name = "carteira"

    def get_queryset(self) -> QuerySet:
        return Carteira.objects.filter(usuario_id=self.request.user.pk)

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(*args, **kwargs)
        context.update(self.kwargs)
        context["href_voltar"] = reverse_lazy("carteiras:listar")
        return context

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        instance = get_object_or_404(
            self.get_queryset(), slug=kwargs.get("slug")
        )
        form = CarteiraForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect("carteiras:listar")
        else:
            return render(request, self.template_name, {"form": form})


class CarteiraExcluir(LoginRequiredBase, DeleteView):
    model = Carteira
    form_class = CarteiraForm
    template_name = "carteiras/carteira_excluir.html"
    context_object_name = "carteira"
    success_url = reverse_lazy("carteiras:listar")

    def get_queryset(self) -> QuerySet:
        return Carteira.objects.filter(usuario_id=self.request.user.pk)

    def get_context_data(self, *args, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(*args, **kwargs)
        context.update(self.kwargs)
        context["href_voltar"] = reverse_lazy("carteiras:listar")
        return context

controle_financeiro/carteiras/templates/carteiras/carteira_atualizar.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block titulo %}Carteiras{% endblock %}

{% block cabecalho %}
<div class="container">
    <h1>Carteira</h1>
    <p>Atualizar cartão registrado.</p>
</div>
{% endblock %}

{% block conteudo %}
{% if form.subject.errors %}
<ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
</ol>
{% endif %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" role="button" type="submit" value="Atualizar">
    <div style="float: right; margin-left: 3px;">
        <a class="btn btn-outline-primary" role="button" href="{{ href_voltar }}">Voltar</a>
    </div>
</form>
{% endblock %}

controle_financeiro/carteiras/templates/carteiras/carteira_criar.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block titulo %}carteiras{% endblock %}

{% block cabecalho %}
<div class="container">
    <h1>Carteira</h1>
    <p>Cadastre sua carteira.</p>
</div>
{% endblock %}

{% block conteudo %}
{% if form.subject.errors %}
<ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
</ol>
{% endif %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" role="button" type="submit" value="Gravar">
    <div style="float: right; margin-left: 3px;">
        <a class="btn btn-outline-primary" role="button" href="{{ href_voltar }}">Voltar</a>
    </div>
</form>
{% endblock %}

controle_financeiro/carteiras/templates/carteiras/carteira_detalhe.html
{% extends "base/template.html" %}
{% load static %}
{% load humanize %}

{% block titulo %}Gerenciamento{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'vendor/flickity/flickity.min.css' %}" media="screen">
<link rel="stylesheet" href="{% static 'css/carteiras/style.css' %}">
{% endblock %}

{% block cabecalho %}
{% endblock %}

{% block conteudo %}
<div class="feed">
    <div class="wrapper-carousel">
        <div class="carousel" data-flickity data-flickity-options='{ "wrapAround": true }'>
            {% for centro_custo in centro_custos %}
            <div class="carousel-cell">
                {% if centro_custo.e_cartao %}
                <a class="nostyle" href="{% url 'carteiras:cartoes:detalhar' carteira.slug centro_custo.cartao.slug %}">
                    <div class="carousel-cartao">
                        <div class="titulo">{{ centro_custo.cartao.nome }}</div>
                        <div class="detalhe">**** **** **** ****</div>
                        <div class="icone">CARTÃO</div>
                        <div class="valor">R$ {{ centro_custo.cartao.valor_total|intcomma }}</div>
                    </div>
                </a>
                {% else %}
                <a class="nostyle" href="{% url 'carteiras:contas:detalhar' carteira.slug centro_custo.conta.slug %}">
                    <div class="carousel-cartao">
                        <div class="titulo">{{ centro_custo.conta.nome }}</div>
                        <div class="detalhe">Agencia: **** Conta: *****-*</div>
                        <div class="icone">CONTA</div>
                        <div class="valor">R$ {{ centro_custo.conta.valor_total|intcomma }}</div>
                    </div>
                </a>
                {% endif %}
            </div>
            {% empty %}
            <div class="carousel-cell-disabled">
                <a class="nostyle" href="{% url 'carteiras:cartoes:criar' carteira.slug %}">
                    <div class="carousel-cartao">
                        <div class="titulo">Meu primeiro cartão ou conta</div>
                        <div class="detalhe"></div>
                        <div class="icone"></div>
                        <div class="valor">R$ 0,00</div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="botao-criar-centro-custo botao botao-primario" onclick="modalCriarContaCartao.open();">+ Conta/Cartão</div>
        {% if centro_custos %}
        <div class="botao-criar-lancamento botao botao-primario" onclick="modalCriarDespesaReceita.open();">+ Despesa/Receita</div>
        {% else %}
        <a class="nostyle botao-criar-lancamento botao botao-primario-inativo" href="#">+ Despesa/Receita</a>
        {% endif %}
    </div>
    {% if lancamentos %}
    <div class="bloco col-12">
        <div class="bloco-ancora"></div>
        <div class="bloco-cabecalho">
            <div class="bloco-titulo">Ultimos Lançamentos</div>
            <a class="bloco-menu nostyle" href="{% url 'carteiras:lancamentos:criar' carteira.slug %}">
                <img class="bloco-menu-icone" src="{% static 'icon/add_gray_24dp.svg' %}" />
            </a>
        </div>
        <div class="bloco-conteudo">
            {% for lancamento in lancamentos %}
            <div class="lancamento-linha">
                <div class="lancamento-logo">?</div>
                <div class="lancamento-titulo">{{ lancamento.descricao}}</div>
                <div class="lancamento-data">{{ lancamento.datahora|date:'d/m/Y H:i' }}</div>
                <div class="lancamento-valor">R$ {{ lancamento.valor|intcomma }}</div>
            </div>
            {% endfor %}
        </div>
        {% if lancamentos_continua %}
        <div class="bloco-rodape"><a class="nostyle" href="{% url 'carteiras:lancamentos:listar' carteira.slug %}">Ver
                mais +</a></div>
        {% endif %}
    </div>
    {% endif %}
</div>

<div id="modalCriarContaCartao" class="modal">
    <div class="modal-content">
        <div class="modal-close" onclick="modalCriarContaCartao.close();">&times;</div>
        <div class="modal-criar-centro-custo">
            <div class="texto">O que deseja adicionar?</div>
            <div class="botao1">
                <a class="nostyle botao botao-primario" href="{% url 'carteiras:cartoes:criar' carteira.slug %}">Cartão</a>
            </div>
            <div class="botao2">
                <a class="nostyle botao botao-primario" href="{% url 'carteiras:contas:criar' carteira.slug %}">Conta</a>
            </div>
        </div>
    </div>
</div>

<div id="modalCriarDespesaReceita" class="modal">
    <div class="modal-content">
        <div class="modal-close" onclick="modalCriarDespesaReceita.close();">&times;</div>
        <div class="modal-criar-centro-custo">
            <div class="texto">O que deseja adicionar?</div>
            <div class="botao1">
                <a class="nostyle botao botao-primario" href="{% url 'carteiras:lancamentos:criar' carteira.slug %}">Despesa</a>
            </div>
            <div class="botao2">
                <a class="nostyle botao botao-primario" href="{% url 'carteiras:lancamentos:criar' carteira.slug %}">Receita</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block script %}
<script src="{% static 'vendor/flickity/flickity.pkgd.min.js' %}"></script>
<script src="{% static 'js/carteiras/script.js' %}"></script>
{% endblock %}

controle_financeiro/carteiras/templates/carteiras/carteira_detalhe_old.html
{% extends "base/base.html" %}
{% load transformar_em_texto %}

{% block titulo %}Carteiras{% endblock %}

{% block cabecalho %}
<div class="container">
  <h1>Carteira</h1>
  <p>Detalhamento da carteira registrada.</p>
</div>
{% endblock %}

{% block conteudo %}
<form>
  <fieldset disabled>
    <div class="mb-3">
      <label for="inputTitulo" class="form-label">Nome</label>
      <input type="text" id="inputTitulo" class="form-control" value="{{ carteira.nome }}">
    </div>
  </fieldset>
</form>
{% if carteira.tem_cartoes %}
<div style="float: left; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button"
    href="{% url 'carteiras:cartoes:listar' carteira.slug %}">Listar Cartões</a>
</div>
{% else %}
<div style="float: left; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button"
    href="{% url 'carteiras:cartoes:criar' carteira.slug %}">Criar Primeiro Cartão</a>
</div>
{% endif %}
{% if carteira.tem_contas %}
<div style="float: left; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button"
    href="{% url 'carteiras:contas:listar' carteira.slug %}">Listar Contas</a>
</div>
{% else %}
<div style="float: left; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button"
    href="{% url 'carteiras:contas:criar' carteira.slug %}">Criar Primeira Conta</a>
</div>
{% endif %}
{% if carteira.tem_centro_custos %}
{% if carteira.tem_lancamentos %}
<div style="float: left; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button"
    href="{% url 'carteiras:lancamentos:listar' carteira.slug %}">Listar Lançamento</a>
</div>
{% else %}
<div style="float: left; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button"
    href="{% url 'carteiras:lancamentos:criar' carteira.slug %}">Criar Lançamento</a>
</div>
{% endif %}
{% endif %}
<div style="float: right; margin-left: 3px;">
  <a class="btn btn-outline-primary" role="button" href="{{ href_voltar }}">Voltar</a>
</div>
{% endblock %}

controle_financeiro/carteiras/templates/carteiras/carteira_excluir.html
{% extends "base/base.html" %}

{% block titulo %}Carteiras{% endblock %}

{% block cabecalho %}
<div class="container">
    <h1>Carteira</h1>
</div>
{% endblock %}

{% block conteudo %}
{% if form.subject.errors %}
<ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
</ol>
{% endif %}
<form method="post">{% csrf_token %}
    <p>
        Você tem certeza que quer apagar a carteira <strong>{{ carteira.nome }}</strong>?
    </p>
    <input class="btn btn-primary" role="button" type="submit" value="Apagar">
    <div style="float: right; margin-left: 3px;">
        <a class="btn btn-outline-primary" role="button" href="{{ href_voltar }}">Voltar</a>
    </div>
</form>
{% endblock %}

controle_financeiro/carteiras/templates/carteiras/carteira_lista.html
{% extends "base/base.html" %}
{% load transformar_em_texto %}

{% block titulo %}Carteiras{% endblock %}

{% block cabecalho %}
<div class="container">
    <h1>Carteira</h1>
    <p>Lista de carteiras registradas.</p>
</div>
{% endblock %}

{% block conteudo %}
<div style="float: right;">
    <p>
        <a class="btn btn-primary" role="button" href="{% url 'carteiras:criar' %}">Criar</a>
    </p>
</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for carteira in carteiras %}
        <tr onclick="window.location='{% url 'carteiras:detalhar' carteira.slug %}'">
            <td>{{ carteira.nome }}</td>
            <td>
                <a href="{% url 'carteiras:editar' carteira.slug %}">editar</a>
                <a href="{% url 'carteiras:excluir' carteira.slug %}">excluir</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include 'base/paginacao.html' %}
<div style="float: right; margin-left: 3px;">
    <a class="btn btn-outline-primary" role="button" href="{{ href_voltar }}">Voltar</a>
</div>
{% endblock %}