controle_financeiro/autenticacao/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path
from .views import LogoutConfirmar, UsuarioCriar

app_name = 'autenticacao'

urlpatterns = [
    # Login/Logout
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/confirmar/', LogoutConfirmar.as_view(), name='logout_confirmar'),
    path('mudar_senha/', PasswordChangeView.as_view(), name='mudar_senha'),
    path('mudar_senha/concluido/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('recuperar_senha/', PasswordResetView.as_view(), name='password_reset'),
    path('recuperar_senha/solicitar/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('recuperar_senha/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('recuperar_senha/concluido/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # Cadastro de usuario
    path('registrar/', UsuarioCriar.as_view(), name='criar'),
]

controle_financeiro/contas/urls.py
from django.urls import path

from .views import (ContaAtualizar, ContaCriar, ContaDetalhe,
                    ContaExcluir, ContaLista)

app_name = 'contas'

urlpatterns = [
    path('', ContaLista.as_view(), name='listar'),
    path('criar', ContaCriar.as_view(), name='criar'),
    path('<slug:slug>', ContaDetalhe.as_view(), name='detalhar'),
    path('<slug:slug>/editar', ContaAtualizar.as_view(), name='editar'),
    path('<slug:slug>/excluir', ContaExcluir.as_view(), name='excluir'),
]

controle_financeiro/paginas/urls.py
from django.urls import path

from .views import IndexView

app_name = 'paginas'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

controle_financeiro/autenticacao/forms.py
import re

from django import forms
from django.utils.translation import gettext_lazy as _
from usuarios.models import Usuario


class RegistroForm(forms.Form):

    REGEX_USERNAME = r'^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){3,18}[a-zA-Z0-9]$'

    username = forms.CharField(
        max_length=100,
        label=_('Usuário'),
        required=True,
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(render_value=False),
        label=_('Senha'),
        required=True,
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(render_value=False),
        label=_('Confirme a senha'),
        required=True,
    )

    first_name = forms.CharField(
        max_length=100,
        label=_('Nome'),
        required=True,
    )

    last_name = forms.CharField(
        max_length=100,
        label=_('Sobrenome'),
        required=True,
    )

    email = forms.EmailField(
        label=_('Email'),
        required=True,
    )

    def clean_username(self):
        if not re.search(self.REGEX_USERNAME, self.cleaned_data['username']):
            raise forms.ValidationError(
                _('Favor use somente letras, números e períodos.')
            )
        if Usuario.objects.filter(
            username__exact=self.cleaned_data['username']
        ).exists():
            raise forms.ValidationError(_('Já existe um usuário com o mesmo nome.'))
        else:
            return self.cleaned_data['username']

    def clean(self):
        if self.cleaned_data.get('password1') != self.cleaned_data.get('password2'):
            raise forms.ValidationError(_('Os dois campos de senha não coincidem.'))
        return self.cleaned_data

controle_financeiro/autenticacao/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, View

from .forms import RegistroForm
from .usecases import registrar_usuario_pessoa_fisica


class LogoutConfirmar(TemplateView):
    template_name = "registration/logout_confirmar.html"


class UsuarioCriar(View):
    form_class = RegistroForm
    template_name = "autenticacao/usuario_criar.html"
    context_object_name = "usuario"

    def get(self, request: HttpRequest) -> HttpResponse:
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request: HttpRequest) -> HttpResponse:
        form = self.form_class(request.POST)
        if form.is_valid():
            registrar_usuario_pessoa_fisica(form)
            return render(request, "autenticacao/usuario_criar_concluido.html", {})
        else:
            return render(request, self.template_name, {"form": form})

controle_financeiro/autenticacao/templates/autenticacao/usuario_criar.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block titulo %}Usuarios{% endblock %}

{% block cabecalho %}
<div class="container">
    <h1>Usuario</h1>
    <p>Crie uma conta para usufruir de nosso conteudo exclusivo.</p>
</div>
{% endblock %}

{% block conteudo %}
{% if form.subject.errors %}
<ol>
    {% for error in form.subject.errors %}
    <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
</ol>
{% endif %}
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" role="button" type="submit" value="Criar">
    <div style="float: right;">
        <a class="btn btn-outline-primary" role="button" href="{% url 'paginas:index' %}">Cancelar</a>
    </div>
</form>
{% endblock %}

controle_financeiro/autenticacao/templates/autenticacao/usuario_criar_concluido.html
{% extends "base/base.html" %}

{% block titulo %}Logout{% endblock %}

{% block cabecalho %}
<div class="container">
  <h1>Usuario</h1>
  <p>Foi criado o usuario com sucesso!</p>
</div>
{% endblock %}

{% block conteudo %}
<a href="{% url 'autenticacao:login'%}">Clique aqui para fazer o login!</a>
{% endblock %}