controle_financeiro/autenticacao/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path
from .views import LogoutConfirmar, UsuarioCriar

app_name = 'autenticacao'

urlpatterns = [
    # Login/Logout
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/confirmar/', LogoutConfirmar.as_view(), name='logout_confirmar'),
    path('mudar_senha/', PasswordChangeView.as_view(), name='mudar_senha'),
    path('mudar_senha/concluido/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('recuperar_senha/', PasswordResetView.as_view(), name='password_reset'),
    path('recuperar_senha/solicitar/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('recuperar_senha/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('recuperar_senha/concluido/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # Cadastro de usuario
    path('registrar/', UsuarioCriar.as_view(), name='criar'),
]

controle_financeiro/contas/urls.py
from django.urls import path

from .views import (ContaAtualizar, ContaCriar, ContaDetalhe,
                    ContaExcluir, ContaLista)

app_name = 'contas'

urlpatterns = [
    path('', ContaLista.as_view(), name='listar'),
    path('criar', ContaCriar.as_view(), name='criar'),
    path('<slug:slug>', ContaDetalhe.as_view(), name='detalhar'),
    path('<slug:slug>/editar', ContaAtualizar.as_view(), name='editar'),
    path('<slug:slug>/excluir', ContaExcluir.as_view(), name='excluir'),
]

controle_financeiro/gerenciamento/urls.py
from django.urls import path
from .views import TemplateExampleView, RedirectView

app_name = "gerenciamento"

urlpatterns = [
    path("", RedirectView.as_view(), name="index"),
    path("template", TemplateExampleView.as_view(), name="example"),
]

controle_financeiro/paginas/urls.py
from django.urls import path

from .views import IndexView

app_name = 'paginas'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

controle_financeiro/base/models.py
from django.db import models


class BaseModel(models.Model):

    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

controle_financeiro/base/forms/monetary.py
import locale
import re
from decimal import Decimal
from typing import Optional

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

locale.setlocale(locale.LC_MONETARY, settings.DEFAULT_LOCALE)

[THOUSAND_POINT, DECIMAL_POINT] = list(
    re.findall(r"[.,]", locale.currency(1234.56, grouping=True, symbol=False))
)

ECMA_ONKEYUP = r'(e=>{const s=(e.value.match(/[0-9]/g)||[]).join("").padStart(3,"0");if("000"===s)e.value="";else{const[t,a]=(parseInt(s,10)/100).toFixed(2).split("."),i=t.split("").reverse().reduce((e,s,t)=>(t<=1?e.push(s):(t+1)%3==1?e.push(`${s}.`):e.push(s),e),[]).reverse().join("");e.value=`${i},${a}`}})(this);'.replace(
    "THOUSAND_POINT", THOUSAND_POINT
).replace(
    "DECIMAL_POINT", DECIMAL_POINT
)


class MonetaryField(forms.Field):
    def __init__(self, *args, **kwargs):
        _attrs = kwargs.pop("attrs", {})
        _attrs.update(
            {
                "onkeyup": ECMA_ONKEYUP,
                "maxlength": 20,
                "placeholder": f"0{DECIMAL_POINT}00",
            }
        )
        kwargs["widget"] = forms.TextInput(attrs=_attrs)
        super().__init__(*args, **kwargs)

    def prepare_value(self, value: Optional[Decimal]) -> str:
        if isinstance(value, Decimal):
            return locale.currency(value, grouping=True, symbol=False)
        else:
            return ""

    def to_python(self, value: Optional[str]) -> Optional[Decimal]:
        try:
            _value = Decimal(
                value.replace(THOUSAND_POINT, "").replace(DECIMAL_POINT, ".")
            )
        except BaseException:
            _value = None
        return _value

    def validate(self, value: Optional[Decimal]):
        super().validate(value)
        if not isinstance(value, Decimal) and self.required is True:
            raise ValidationError(_("This field is required."), code="required")

controle_financeiro/base/forms/monetary_input.py
import locale
import re
from decimal import Decimal
from typing import Optional

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

locale.setlocale(locale.LC_MONETARY, settings.DEFAULT_LOCALE)

[THOUSAND_POINT, DECIMAL_POINT] = list(
    re.findall(r"[.,]", locale.currency(1234.56, grouping=True, symbol=False))
)

ECMA_ONKEYUP = (r'(e=>{const s=e.value.replace(/[\D]+/g,"");if(s){const[p,r]=(parseInt(s)/100).toFixed(2).split("."),t=`${p.split("").reverse().reduce((e,s,p)=>(p<=1?e.push(s):(p+1)%3==1?e.push(`${s}THOUSAND_POINT`):e.push(s),e),[]).reverse().join("")}DECIMAL_POINT${r}`;e.value=t}})(this);'
                .replace("THOUSAND_POINT", THOUSAND_POINT)
                .replace("DECIMAL_POINT", DECIMAL_POINT))


class MonetaryInput(forms.Field):
    def __init__(self, *args, **kwargs):
        kwargs["widget"] = forms.TextInput(attrs={"onkeyup": ECMA_ONKEYUP})
        super().__init__(*args, **kwargs)

    def prepare_value(self, value: Optional[Decimal]) -> str:
        if isinstance(value, Decimal):
            return locale.currency(value, grouping=True, symbol=False)
        else:
            return ""

    def to_python(self, value: Optional[str]) -> Optional[Decimal]:
        try:
            _value = Decimal(
                value.replace(THOUSAND_POINT, "").replace(DECIMAL_POINT, ".")
            )
        except BaseException:
            _value = None
        return _value

    def validate(self, value: Optional[Decimal]):
        super().validate(value)
        if not isinstance(value, Decimal):
            raise ValidationError(_("Invalid value"), code="invalid")

controle_financeiro/base/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class LoginRequiredBase(LoginRequiredMixin):
    login_url = reverse_lazy('autenticacao:login')
    redirect_field_name = 'redirect_to'

controle_financeiro/base/templates/base/includes/barra_navegacao.html
{% load dom_efeitos %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'paginas:index' %}">ControleFinanceiro</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                <li class="nav-item{{ request|nav_item_active:'carteiras' }}">
                    <a class="nav-link" href="{% url 'gerenciamento:index' %}">Gerenciamento</a>
                </li>
                <li class="nav-item{{ request|nav_item_active:'registration,autenticacao' }}">
                    <a class="nav-link" href="{% url 'autenticacao:logout_confirmar' %}">
                        {{ request.user.nome_apresentacao }}{% if request|span_sr_only:'registration,autenticacao' %} <span class="sr-only">(current)</span>{% endif %}
                        > Logout
                    </a>
                </li>
                {% else %}
                <li class="nav-item{{ request|nav_item_active:'registration,autenticacao' }}">
                    <a class="nav-link" href="{% url 'autenticacao:login' %}">Login/Registrar{% if request|span_sr_only:'registration,autenticacao' %} <span class="sr-only">(current)</span>{% endif %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

controle_financeiro/base/templates/base/includes/barra_superior.html
{% load static %}
<nav class="barra-superior">
    <a class="nostyle"
        href="{% if request.user.is_authenticated %}{% url 'gerenciamento:index' %}{% else %}{% url 'paginas:index' %}{% endif %}">
        <div class="barra-superior-logo">C.FINANCEIRO</div>
    </a>
    <div class="barra-superior-menu">
        <div class="botao-menu-lateral" onclick="menuLateralAbrir(true)">
            {% if request.user.is_authenticated %}
            <div class="usuario-nome">{{ request.user.nome_apresentacao }}</div>
            <div class="usuario-foto">
                    <img class="usuario-icone" src="{% static 'icon/person_gray_24dp.svg' %}" />
            </div>
            {% else %}
            <div class="botao-menu">
                <div>
                    <div class="hamburguer-linha"></div>
                    <div class="hamburguer-linha"></div>
                    <div class="hamburguer-linha"></div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</nav>

controle_financeiro/base/templates/base/includes/menu_lateral.html
{% load dom_efeitos %}
<aside>
    <div class="menu-lateral-2-plano menu-lateral-2-plano-fechado" onclick="menuLateralAbrir(false)"></div>
    <div class="menu-lateral menu-lateral-fechado">
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item{{ request|nav_item_active:'carteiras' }}">
                <a class="nostyle" href="{% url 'gerenciamento:index' %}">Gerenciamento</a>
            </li>
            <li class="nav-item{{ request|nav_item_active:'registration,autenticacao' }}">
                <a class="nostyle" href="{% url 'autenticacao:logout_confirmar' %}">
                    {{ request.user.nome_apresentacao }}{% if request|span_sr_only:'registration,autenticacao' %} <span
                        class="sr-only">(current)</span>{% endif %}
                    > Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item{{ request|nav_item_active:'registration,autenticacao' }}">
                <a class="nostyle" href="{% url 'autenticacao:login' %}">Login/Registrar{% if
                    request|span_sr_only:'registration,autenticacao' %} <span class="sr-only">(current)</span>{% endif
                    %}</a>
            </li>
            {% endif %}
        </ul>
    </div>
</aside>